name: CI

on:
  push:
    branches:
      - master
      - staging
      - trying
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run clippy
        run: cargo clippy --verbose --all --tests

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check formatting
        run: cargo fmt --all -- --check

  publish_snap:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [build, clippy, format]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        with:
          use_lxd: true
          snapcraft_token: ${{ secrets.snapcraft_token }}

      - name: Install review tools
        run: sudo snap install review-tools

      - name: Build snap
        run: sg lxd -c 'snapcraft --use-lxd'

      - name: Publish snap
        run: snapcraft upload ./uefi-run_*.snap --release edge
